name: Build and test

on:
  push:
  pull_request:

jobs:
  build_test:
    name: Build and test
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker image
      run: docker build --target=builder -t retropilot-client:builder .
    - name: Run tests
      run: docker run --rm --env CI=true retropilot-client:builder npm test
